### ISSUE TITLE
Guided setup hangs during "Finishing Setup"

### ISSUE THREAD

**Issue by andym** [bang-olufsen/create#32]
Steps to reproduce :-

- Start with a fresh install of raspbian stretch lite.
- Download the beocreate-installer script (repo is currently at 96605b5 )
- Run the installer, wait for it to install, rename the host and reboot.
- Use the guided setup to connect to the system, select a sound profile, select a hostname
- At the final step the status at the bottom says "Sound Profile..." and the animated spinner spins, but it doesn't progress any further.

Reconnecting to the system takes you back to the "finishing setup" page with a status of "Sound Profile...". 

SSH-ing to the host shows it still has the original "beocreate-4ch-blank" hostname.
I'm using a new 4CA with the jumpers untouched.

**Comment by andym** [comment]
`forever list`

Shows that` /home/pi/beocreate-server.js` is running, but the logs it references are empty.

**Comment by andym** [comment]
If I restart from scratch and modify the beocreate-installer script like this:

```
        git clone https://github.com/bang-olufsen/create.git
        cd create
        git reset --hard 309463bca002ac95c030b48f0a0dab9c7aa319c
```

Then I'm able to reach the end of the guided setup process. The host restarts and works nicely.

**Comment by tuomashamalainen** [comment]
We noticed the same a few days ago. The reason for the stall is that SigmaTcpDaemon crashes when the server instructs it to flash the 4CA self-boot EEPROM, producing the following error:
`*** Error in '/home/pi/create/SigmaTcpDaemon/sigmaTcpDaemon': malloc(): memory corruption: 0x76300008 ***`
Thanks for the lead – I'll investigate more.

**Comment by tuomashamalainen** [comment]
Follow-up to the previous: indeed using the daemon version from before its latest bugfix works, with everything else otherwise in the current state of `master`.

The bugfix specifically addressed an issue where reading from the DSP returns incorrect values. Whilst this is an important fix for the future, we're currently not using the read functionality as a part of ReCreate. Thus it would be possible to roll back the change without affecting the "core" experience, unless it's an easy fix and we can then have the cake and eat it too.

Thoughts, @c-larsen?

**Comment by tuomashamalainen** [comment]
Closing this for now, since we rolled back the fix that caused this problem in the first place.
