### ISSUE TITLE
Improvement: Use systemd for daemon start

### ISSUE THREAD

**Issue by hifiberry** [bang-olufsen/create#39]
There are still "old-style" init scripts uses. These should be migrated to systemd unit files.

**Comment by tuomashamalainen** [comment]
I'm actually thinking that if we restructure some things a bit, we can simplify the system startup routine. These are the commands currently in the init.d script:
```
# Reset SigmaDSP:
echo "Resetting SigmaDSP..."
/home/pi/bin/sigmareset
	
# Setting master volume:
amixer sset 'Master' 90%

# Start SigmaDSP daemon:
echo "Starting SigmaDSP daemon..."
/home/pi/create/SigmaTcpDaemon/sigmaTcpDaemon > /dev/null &
	
sleep 2

# Start the remote control server:
echo "Starting remote control server..."
forever start -s /home/pi/beocreate-server.js

# Play the startup sound:
echo "Playing startup sound..."
aplay -q /home/pi/Music/startup.wav
```

My thoughts on what to do to them:

- DSP reset can be performed from the Node server. I keep thinking if it's still necessary, but it might be in cases where the system is soft-rebooted – we want the DSP to "reboot" too so it's a fresh slate to apply real-time sound adjustments to.
- The reason we use amixer to set master volume to 90% is because of the odd volume control behaviour of *bt-speaker* with some devices, where there are no AVRCP commands but the source adjusts volume at its end. For now, this can also move into the Node program, but preferably we can fix the original issue and remove it. At the moment I'm clueless as to what it would take.
- For DSP communication, we'll adopt HiFiBerry [DSPToolkit](https://github.com/hifiberry/hifiberry-dsp). It includes an all-new *SigmaTCPServer*, which comes with its own systemd unit file and starts automatically anyway, as I understand it. It means this step is no longer required.
- Startup tone playback can be moved into the Node program. This is trivial, as *aplay* module is already included and used for the voice announcements.
- Finally, assuming all of the above, we won't need a separate startup script anymore, and the new systemd unit file can just start Node directly, also eliminating the need to use *forever*, which we've used thus far to start the server and keep it running.

**Comment by tuomashamalainen** [comment]
Beocreate 2 now uses a systemd unit file for startup, also implementing the other previously described changes.
