### ISSUE TITLE
Audikast and Bt_speaker

### ISSUE THREAD

**Issue by calimero2312** [bang-olufsen/create#45]
First, I am not a BT expert and discovered most of those things recently so it s possible that the terminology is not accurate: Apologies in advance
Here is the idea (maybe of interest to other and ok to share). I am trying to connect an avantree audikast (that has the capacity to pair two bt speakers or headsets and thus can broadcast analogic audio to Bluetooth (codec sbc or aptx depending on the receiver)) to two beocreate powered RL-6000 speakers.  I did the preliminary check and the unit works well with two Jabra headsets connected.
I got a hard time to figure out how to connect the unit to the beocreate speakers : the  unit is in listen mode and was not detecting the speakers until I change the Class of the beocreate to class 0x04041c or  0x240404) which corresponds to audio/video  Major device class. Since I am able to briefly hear a distorted sound and then silence. Also the class is always reverting back to 0x040000

I join a dumpfile of the Bluetooth on the pi (sudo hcidump hci0)
And the description info of the audikast as seen by pi bleutooth when connected 

I know that it may be too much to ask but any insights/idea to explore is welcome 

Thanks in advance

Best

Alexis
[dumpfile.txt](https://github.com/bang-olufsen/create/files/2552592/dumpfile.txt)
[audikast.txt](https://github.com/bang-olufsen/create/files/2552593/audikast.txt)

**Comment by tuomashamalainen** [comment]
Hi Alexis,

Thanks for your message, I just wanted to acknowledge that I've seen it, although I can't offer a resolution at this time.

Bluetooth audio on BeoCreate needs a lot of work, but I haven't had the time to look into it.

We decided to use [bt-speaker](https://github.com/lukasjapan/bt-speaker/) to implement Bluetooth audio. At the time it was the best solution – I don't know if newer/better projects have emerged since then. We [forked the project](https://github.com/c-larsen/bt-speaker/) to make a few small changes, the most relevant being turning Raspberry Pi's built-in Wi-Fi off during a Bluetooth audio session to prevent dropouts. 

Keeping this in mind, I would recommend checking out the original project and opening an issue there if it persists (my guess is yes – we didn't make changes to the actual Bluetooth implementation) – although there doesn't seem to be a lot of activity.

**Comment by calimero2312** [comment]
Hi Tuomas,

Thanks already for the acknowledgement. I looked also on the original repository but as you noticed indeed there is little activity.
Thanks anyway, I am really happy (already) with the beocreate and think that this is a very nice project and I am truly hoping that it will have a long future. Depending of my time  and capacity  I will try to explore more 

Best

Alexis

**Comment by tuomashamalainen** [comment]
I'll close this one now. Beocreate 2 + HiFiBerryOS includes a new Bluetooth implementation.
